name: Build, Deploy to ECS, and Manage Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t chinni111/medusa:latest .

    - name: Test Docker image
      run: |
        docker run -d -p 80:80 --name medusa_test chinni111/medusa:latest
        sleep 30  # Wait for the container to start
        curl -f http://localhost:80 || exit 1  # Verify the application is running
        docker stop medusa_test
        docker rm medusa_test

    - name: Push Docker image
      run: |
        docker push chinni111/medusa:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify your Terraform version

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-definition.json
        service: medusa-service
        cluster: medusa-cluster
        wait-for-service-stability: true
        region: us-east-1

